### ISSUE TITLE
Any plan to separate into zig-curses wrapper library?

### ISSUE THREAD

**Issue by bivoje** [Akuli/curses-minesweeper#4]
Not sure if this is the right place to ask, but do you have any plan to separate your wrapper code for curses as a separate library?
I'm really enjoying your work done here and thought I want to use it in my project too!
Since the code is under MIT license, if you don't mind, I'd like to make zig curses wrapper library based on your code.
Let me know if you were to do so yourself, I would wait for it.

Thanks!

**Comment by Akuli** [comment]
Feel free to make a curses wrapper library based on this project, and if you want, a pull request that changes this project to use it :)

**Comment by bivoje** [comment]
Ok then, I'll get to work on it and comment here with PR when it's done. Thanks!

**Comment by Akuli** [comment]
I am no longer interested in adding a library as a dependency, because it means I cannot upgrade this project to newer Zig version if the library doesn't. That said, feel free to make such a library from my code if you want :)
