### ISSUE TITLE
can't build on 0.11

### ISSUE THREAD

**Issue by vkensou** [Akuli/curses-minesweeper#5]
could you fix the build errors?

**Comment by Akuli** [comment]
Could you? :)

I will happily accept a PR that fixes stuff, but won't have time/motivation to do it myself any time soon.

**Comment by vkensou** [comment]
> Could you? :)
> 
> I will happily accept a PR that fixes stuff, but won't have time/motivation to do it myself any time soon.

Sorry, I am a learner of Zig. I found your project through the awesome-zig repository and then found it failed to compile.

**Comment by Akuli** [comment]
I started working on this. Apparently zig-clap doesn't support 0.11 yet, which is not surprising, since 0.11 has only been out for a week.

Maybe I will first try to upgrade this project to 0.10.

**Comment by Lamby777** [comment]
`zig-clap` for 0.11.0 is out... but now zig master is 0.12.0 lol
Is it worth updating to 0.11.0 or just to wait for `zig-clap` on 0.12.0?
<https://github.com/Hejsil/zig-clap/releases/tag/0.7.0>

I remember running into that exact issue after updating the rest of the code to 0.11.0... was a while ago; I deleted it, so I don't have it anymore, though... ;-;

**Comment by Akuli** [comment]
I will accept a PR updating to 0.11.0 or 0.12.0.

**Comment by Akuli** [comment]
Thanks for reminding me about this project by closing your PR (that sent a notification to my email). I have now updated the project to Zig 0.13.0.
